model:
  name: Customized("mnist_custom_model_data", "simple_mlp_model")

data:
  dataset: Customized("mnist_custom_model_data", "mnist_dataset")
  mean: [0.0]
  std: [1.0]

specification:
  epsilon: 0.1
  norm: .inf

solver:
  batch_size: 64

bab:
  timeout: 300 